/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SkillForgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedValidators"
      | "badges"
      | "calculateTotalScore"
      | "claimBadge"
      | "confidentialProtocolId"
      | "courses"
      | "forgeCourse"
      | "getBadge"
      | "getBadgeEncryptedScore"
      | "getCourse"
      | "getProof"
      | "getProofEncryptedScore"
      | "grantValidatorRole"
      | "nextBadgeId"
      | "nextCourseId"
      | "nextProofId"
      | "proofs"
      | "submitProof"
      | "updateCourseChallenges"
      | "validateProof"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BadgeClaimed"
      | "CourseForged"
      | "ProofSubmitted"
      | "ProofValidated"
      | "ValidatorGranted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedValidators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "badges",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTotalScore",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimBadge",
    values: [BigNumberish, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "courses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forgeCourse",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBadge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBadgeEncryptedScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCourse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProof",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProofEncryptedScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantValidatorRole",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "nextBadgeId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextCourseId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextProofId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proofs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BigNumberish, BigNumberish, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCourseChallenges",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateProof",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "badges", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateTotalScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimBadge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "courses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "forgeCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBadge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBadgeEncryptedScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCourse", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getProof", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProofEncryptedScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantValidatorRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextBadgeId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextCourseId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextProofId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proofs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCourseChallenges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateProof",
    data: BytesLike
  ): Result;
}

export namespace BadgeClaimedEvent {
  export type InputTuple = [
    badgeId: BigNumberish,
    courseId: BigNumberish,
    earner: AddressLike,
    badgeCID: string
  ];
  export type OutputTuple = [
    badgeId: bigint,
    courseId: bigint,
    earner: string,
    badgeCID: string
  ];
  export interface OutputObject {
    badgeId: bigint;
    courseId: bigint;
    earner: string;
    badgeCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CourseForgedEvent {
  export type InputTuple = [
    courseId: BigNumberish,
    creator: AddressLike,
    courseCID: string
  ];
  export type OutputTuple = [
    courseId: bigint,
    creator: string,
    courseCID: string
  ];
  export interface OutputObject {
    courseId: bigint;
    creator: string;
    courseCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofSubmittedEvent {
  export type InputTuple = [
    proofId: BigNumberish,
    courseId: BigNumberish,
    learner: AddressLike,
    proofCID: string
  ];
  export type OutputTuple = [
    proofId: bigint,
    courseId: bigint,
    learner: string,
    proofCID: string
  ];
  export interface OutputObject {
    proofId: bigint;
    courseId: bigint;
    learner: string;
    proofCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofValidatedEvent {
  export type InputTuple = [
    proofId: BigNumberish,
    validator: AddressLike,
    status: BigNumberish
  ];
  export type OutputTuple = [
    proofId: bigint,
    validator: string,
    status: bigint
  ];
  export interface OutputObject {
    proofId: bigint;
    validator: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorGrantedEvent {
  export type InputTuple = [validator: AddressLike, authorized: boolean];
  export type OutputTuple = [validator: string, authorized: boolean];
  export interface OutputObject {
    validator: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SkillForge extends BaseContract {
  connect(runner?: ContractRunner | null): SkillForge;
  waitForDeployment(): Promise<this>;

  interface: SkillForgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedValidators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  badges: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        courseId: bigint;
        earner: string;
        badgeCID: string;
        encryptedTotalScore: string;
        claimedAt: bigint;
      }
    ],
    "view"
  >;

  calculateTotalScore: TypedContractMethod<
    [proofIds: BigNumberish[]],
    [string],
    "nonpayable"
  >;

  claimBadge: TypedContractMethod<
    [
      courseId: BigNumberish,
      badgeCID: string,
      encryptedTotalScore: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  courses: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, boolean, bigint] & {
        creator: string;
        courseCID: string;
        totalChallenges: string;
        completedChallenges: string;
        active: boolean;
        forgedAt: bigint;
      }
    ],
    "view"
  >;

  forgeCourse: TypedContractMethod<
    [
      courseCID: string,
      encryptedTotalChallenges: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getBadge: TypedContractMethod<
    [badgeId: BigNumberish],
    [
      [bigint, string, string, bigint] & {
        courseId: bigint;
        earner: string;
        badgeCID: string;
        claimedAt: bigint;
      }
    ],
    "view"
  >;

  getBadgeEncryptedScore: TypedContractMethod<
    [badgeId: BigNumberish],
    [string],
    "view"
  >;

  getCourse: TypedContractMethod<
    [courseId: BigNumberish],
    [
      [string, string, boolean, bigint] & {
        creator: string;
        courseCID: string;
        active: boolean;
        forgedAt: bigint;
      }
    ],
    "view"
  >;

  getProof: TypedContractMethod<
    [proofId: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, string, bigint] & {
        courseId: bigint;
        challengeId: bigint;
        learner: string;
        proofCID: string;
        status: bigint;
        validator: string;
        submittedAt: bigint;
      }
    ],
    "view"
  >;

  getProofEncryptedScore: TypedContractMethod<
    [proofId: BigNumberish],
    [string],
    "view"
  >;

  grantValidatorRole: TypedContractMethod<
    [validator: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  nextBadgeId: TypedContractMethod<[], [bigint], "view">;

  nextCourseId: TypedContractMethod<[], [bigint], "view">;

  nextProofId: TypedContractMethod<[], [bigint], "view">;

  proofs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        courseId: bigint;
        challengeId: bigint;
        learner: string;
        proofCID: string;
        encryptedScore: string;
        status: bigint;
        validator: string;
        submittedAt: bigint;
        validatedAt: bigint;
      }
    ],
    "view"
  >;

  submitProof: TypedContractMethod<
    [
      courseId: BigNumberish,
      challengeId: BigNumberish,
      proofCID: string,
      encryptedScore: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  updateCourseChallenges: TypedContractMethod<
    [
      courseId: BigNumberish,
      encryptedTotalChallenges: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  validateProof: TypedContractMethod<
    [
      proofId: BigNumberish,
      status: BigNumberish,
      newEncryptedScore: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedValidators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "badges"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        courseId: bigint;
        earner: string;
        badgeCID: string;
        encryptedTotalScore: string;
        claimedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateTotalScore"
  ): TypedContractMethod<[proofIds: BigNumberish[]], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "claimBadge"
  ): TypedContractMethod<
    [
      courseId: BigNumberish,
      badgeCID: string,
      encryptedTotalScore: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "courses"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, boolean, bigint] & {
        creator: string;
        courseCID: string;
        totalChallenges: string;
        completedChallenges: string;
        active: boolean;
        forgedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "forgeCourse"
  ): TypedContractMethod<
    [
      courseCID: string,
      encryptedTotalChallenges: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBadge"
  ): TypedContractMethod<
    [badgeId: BigNumberish],
    [
      [bigint, string, string, bigint] & {
        courseId: bigint;
        earner: string;
        badgeCID: string;
        claimedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBadgeEncryptedScore"
  ): TypedContractMethod<[badgeId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCourse"
  ): TypedContractMethod<
    [courseId: BigNumberish],
    [
      [string, string, boolean, bigint] & {
        creator: string;
        courseCID: string;
        active: boolean;
        forgedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProof"
  ): TypedContractMethod<
    [proofId: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, string, bigint] & {
        courseId: bigint;
        challengeId: bigint;
        learner: string;
        proofCID: string;
        status: bigint;
        validator: string;
        submittedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProofEncryptedScore"
  ): TypedContractMethod<[proofId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "grantValidatorRole"
  ): TypedContractMethod<
    [validator: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextBadgeId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextCourseId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextProofId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proofs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        courseId: bigint;
        challengeId: bigint;
        learner: string;
        proofCID: string;
        encryptedScore: string;
        status: bigint;
        validator: string;
        submittedAt: bigint;
        validatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [
      courseId: BigNumberish,
      challengeId: BigNumberish,
      proofCID: string,
      encryptedScore: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCourseChallenges"
  ): TypedContractMethod<
    [
      courseId: BigNumberish,
      encryptedTotalChallenges: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateProof"
  ): TypedContractMethod<
    [
      proofId: BigNumberish,
      status: BigNumberish,
      newEncryptedScore: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BadgeClaimed"
  ): TypedContractEvent<
    BadgeClaimedEvent.InputTuple,
    BadgeClaimedEvent.OutputTuple,
    BadgeClaimedEvent.OutputObject
  >;
  getEvent(
    key: "CourseForged"
  ): TypedContractEvent<
    CourseForgedEvent.InputTuple,
    CourseForgedEvent.OutputTuple,
    CourseForgedEvent.OutputObject
  >;
  getEvent(
    key: "ProofSubmitted"
  ): TypedContractEvent<
    ProofSubmittedEvent.InputTuple,
    ProofSubmittedEvent.OutputTuple,
    ProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ProofValidated"
  ): TypedContractEvent<
    ProofValidatedEvent.InputTuple,
    ProofValidatedEvent.OutputTuple,
    ProofValidatedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorGranted"
  ): TypedContractEvent<
    ValidatorGrantedEvent.InputTuple,
    ValidatorGrantedEvent.OutputTuple,
    ValidatorGrantedEvent.OutputObject
  >;

  filters: {
    "BadgeClaimed(uint256,uint256,address,string)": TypedContractEvent<
      BadgeClaimedEvent.InputTuple,
      BadgeClaimedEvent.OutputTuple,
      BadgeClaimedEvent.OutputObject
    >;
    BadgeClaimed: TypedContractEvent<
      BadgeClaimedEvent.InputTuple,
      BadgeClaimedEvent.OutputTuple,
      BadgeClaimedEvent.OutputObject
    >;

    "CourseForged(uint256,address,string)": TypedContractEvent<
      CourseForgedEvent.InputTuple,
      CourseForgedEvent.OutputTuple,
      CourseForgedEvent.OutputObject
    >;
    CourseForged: TypedContractEvent<
      CourseForgedEvent.InputTuple,
      CourseForgedEvent.OutputTuple,
      CourseForgedEvent.OutputObject
    >;

    "ProofSubmitted(uint256,uint256,address,string)": TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;
    ProofSubmitted: TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;

    "ProofValidated(uint256,address,uint8)": TypedContractEvent<
      ProofValidatedEvent.InputTuple,
      ProofValidatedEvent.OutputTuple,
      ProofValidatedEvent.OutputObject
    >;
    ProofValidated: TypedContractEvent<
      ProofValidatedEvent.InputTuple,
      ProofValidatedEvent.OutputTuple,
      ProofValidatedEvent.OutputObject
    >;

    "ValidatorGranted(address,bool)": TypedContractEvent<
      ValidatorGrantedEvent.InputTuple,
      ValidatorGrantedEvent.OutputTuple,
      ValidatorGrantedEvent.OutputObject
    >;
    ValidatorGranted: TypedContractEvent<
      ValidatorGrantedEvent.InputTuple,
      ValidatorGrantedEvent.OutputTuple,
      ValidatorGrantedEvent.OutputObject
    >;
  };
}
